name: BuildersWand
version: '${version}'
main: com.playtheatria.buildersWand.BuildersWandPlugin
api-version: '26.1'
softdepend: [WorldGuard, Lands]
commands:
  wand:
    description: The Builders Wand materializer
    usage: /wand [give|form] [args]
permissions:
  builderswand.use:
    description: Use the Builders Wand and /wand form
    default: op
  builderswand.give:
    description: Give a Builders Wand
    default: op
